import {beforeEach, describe, expect, it} from "vitest";
import {
  BLS_VERIFIER_MAX_BATCH_SIZE,
  BLS_VERIFIER_MAX_SAME_MESSAGE_BATCH_SIZE,
  BLS_VERIFIER_SET_TYPE,
  type BlsSignatureSet,
  verifySignatureSets,
  verifySignatureSetsSameMessage,
} from "../src/bls-verifier.js";
import {PublicKey, SecretKey, Signature, aggregateSignatures} from "../src/blst.js";
import {pubkeyCache} from "../src/pubkeys.js";

const keys = Array.from({length: 4}, (_, i) => {
  const ikm = new Uint8Array(32);
  ikm[0] = i + 1;
  return SecretKey.fromKeygen(ikm);
});

function message(value: number): Uint8Array {
  return new Uint8Array(32).fill(value);
}

function infinityPoint(length: number): Uint8Array {
  const point = new Uint8Array(length);
  point[0] = 0xc0;
  return point;
}

/**
 * Generated by adding [r]P to `keys[0]`'s public key. `r` is the BLS12-381
 * subgroup order. `P` is the first decodable compressed G1 point after x=0,
 * which blst rejects specially; its x-coordinate is 4. The result decodes but
 * is outside G1.
 *
 * Repro with SageMathCell: https://sagecell.sagemath.org/?q=zwkoch
 */
const G1_PUBLIC_KEY_WITH_TORSION = Uint8Array.from(
  Buffer.from("8e47d02ba5dda27d4ec148cc45e8def137251a6e78d67f9d4b3e016f6bf97cf0c9eaf7934c75dfa2f3c094314d6ab5dd", "hex")
);
/**
 * Generated by adding [r]P to the valid signature made with an all-0x01 IKM
 * and an all-0x02 message. `P` is the first decodable compressed G2 point with
 * an x-coordinate in the range 0 through 255. The result decodes but is outside
 * G2.
 *
 * Repro with SageMathCell: https://sagecell.sagemath.org/?q=zwkoch
 */
const G2_SIGNATURE_WITH_TORSION = Uint8Array.from(
  Buffer.from(
    "99de7bff0cf5337f1d09fec80f5c9f5af01436b61656692b9520ca79f8211266" +
      "8bbedce24f69d56c171a39b0425e508017c04962b77d77d80233bd92f45ba9bb" +
      "93917964f576e8c5a1d2b9487c1e9b0d99021fb8ecfe5fec421d41c19674b609",
    "hex"
  )
);

describe("bls verifier", () => {
  beforeEach(() => {
    pubkeyCache.reset();
    for (const [index, key] of keys.entries()) {
      pubkeyCache.append(index, key.toPublicKey().toBytes());
    }
  });

  it("exports native verifier limits and set type enum", () => {
    expect(BLS_VERIFIER_SET_TYPE).toEqual({aggregate: 1, indexed: 0, single: 2});
    expect(BLS_VERIFIER_MAX_BATCH_SIZE).toBe(256);
    expect(BLS_VERIFIER_MAX_SAME_MESSAGE_BATCH_SIZE).toBe(128);
  });

  it("verifies mixed indexed, aggregate, and raw-pubkey sets", () => {
    const indexedMessage = message(1);
    const aggregateMessage = message(2);
    const singleMessage = message(3);
    const aggregateSignature = aggregateSignatures([keys[1].sign(aggregateMessage), keys[2].sign(aggregateMessage)]);

    const sets: BlsSignatureSet[] = [
      {
        index: 0,
        message: indexedMessage,
        signature: keys[0].sign(indexedMessage).toBytes(),
        type: BLS_VERIFIER_SET_TYPE.indexed,
      },
      {
        indices: Uint32Array.from([1, 2]),
        message: aggregateMessage,
        signature: aggregateSignature.toBytes(),
        type: BLS_VERIFIER_SET_TYPE.aggregate,
      },
      {
        message: singleMessage,
        pubkey: keys[3].toPublicKey().toBytes(),
        signature: keys[3].sign(singleMessage).toBytes(),
        type: BLS_VERIFIER_SET_TYPE.single,
      },
    ];

    expect(verifySignatureSets(sets)).toBe(true);
  });

  it("returns false for invalid cryptographic input", () => {
    expect(
      verifySignatureSets([
        {
          index: 0,
          message: message(1),
          signature: new Uint8Array(96),
          type: BLS_VERIFIER_SET_TYPE.indexed,
        },
      ])
    ).toBe(false);
  });

  it("rejects infinity and subgroup-invalid points before pairing", () => {
    const signingRoot = message(2);
    const validSignature = keys[0].sign(signingRoot).toBytes();
    const validPublicKey = keys[0].toPublicKey().toBytes();
    const missingCacheSet: BlsSignatureSet = {
      index: keys.length,
      message: signingRoot,
      signature: validSignature,
      type: BLS_VERIFIER_SET_TYPE.indexed,
    };
    const infinityPublicKey = infinityPoint(PublicKey.COMPRESS_SIZE);
    const infinitySignature = infinityPoint(Signature.COMPRESS_SIZE);

    expect(() => PublicKey.fromBytes(infinityPublicKey).validate()).toThrow("PkIsInfinity");
    expect(() => PublicKey.fromBytes(G1_PUBLIC_KEY_WITH_TORSION).validate()).toThrow("PointNotInGroup");
    expect(() => Signature.fromBytes(infinitySignature).validate(true)).toThrow("InvalidSignature");
    expect(() => Signature.fromBytes(G2_SIGNATURE_WITH_TORSION).validate(true)).toThrow("InvalidSignature");

    // Coupling tests with missingCacheSet to prove that verification returns false
    // prior to throwing for a missing pubkey
    // Test with valid message + signature, invalid pk
    for (const invalidPubkey of [infinityPublicKey, G1_PUBLIC_KEY_WITH_TORSION]) {
      expect(
        verifySignatureSets([
          {message: signingRoot, pubkey: invalidPubkey, signature: validSignature, type: BLS_VERIFIER_SET_TYPE.single},
          missingCacheSet,
        ])
      ).toBe(false);
    }

    // Coupling tests with missingCacheSet to prove that verification returns false
    // prior to throwing for a missing pubkey
    // Test with valid message + pk, invalid signature
    for (const invalidSignature of [infinitySignature, G2_SIGNATURE_WITH_TORSION]) {
      const invalidSets: BlsSignatureSet[] = [
        {index: 0, message: signingRoot, signature: invalidSignature, type: BLS_VERIFIER_SET_TYPE.indexed},
        {message: signingRoot, pubkey: validPublicKey, signature: invalidSignature, type: BLS_VERIFIER_SET_TYPE.single},
      ];
      for (const invalidSet of invalidSets) {
        expect(verifySignatureSets([invalidSet, missingCacheSet])).toBe(false);
      }
    }

    expect(
      verifySignatureSetsSameMessage(
        [
          // valid message + pk, invalid signature
          {index: 0, signature: infinitySignature},
          // valid message + signature, invalid pk
          {index: 1, signature: G2_SIGNATURE_WITH_TORSION},
        ],
        signingRoot
      )
    ).toEqual([false, false]);
  });

  it("throws for a missing cached validator index", () => {
    const signingRoot = message(1);
    expect(() =>
      verifySignatureSets([
        {
          index: keys.length,
          message: signingRoot,
          signature: keys[0].sign(signingRoot).toBytes(),
          type: BLS_VERIFIER_SET_TYPE.indexed,
        },
      ])
    ).toThrow("PubkeyIndexNotFound");

    expect(() =>
      verifySignatureSetsSameMessage(
        [{index: keys.length, signature: keys[0].sign(signingRoot).toBytes()}],
        signingRoot
      )
    ).toThrow("PubkeyIndexNotFound");
  });

  it("short-circuits after an invalid cryptographic input", () => {
    const signingRoot = message(1);
    const invalidSet: BlsSignatureSet = {
      index: 0,
      message: signingRoot,
      signature: new Uint8Array(96),
      type: BLS_VERIFIER_SET_TYPE.indexed,
    };
    const missingCacheSet: BlsSignatureSet = {
      index: keys.length,
      message: signingRoot,
      signature: keys[0].sign(signingRoot).toBytes(),
      type: BLS_VERIFIER_SET_TYPE.indexed,
    };

    expect(verifySignatureSets([invalidSet, missingCacheSet])).toBe(false);
    expect(() => verifySignatureSets([missingCacheSet, invalidSet])).toThrow("PubkeyIndexNotFound");
  });

  it("randomly aggregates indexed signatures over the same message", () => {
    const signingRoot = message(4);
    const sets = keys.map((key, index) => ({
      index,
      signature: key.sign(signingRoot).toBytes(),
    }));

    expect(verifySignatureSetsSameMessage(sets, signingRoot)).toEqual([true, true, true, true]);

    sets[1] = {...sets[1], signature: keys[1].sign(message(5)).toBytes()};
    expect(verifySignatureSetsSameMessage(sets, signingRoot)).toEqual([true, false, true, true]);

    sets[1] = {...sets[1], signature: new Uint8Array(96)};
    expect(verifySignatureSetsSameMessage(sets, signingRoot)).toEqual([true, false, true, true]);
  });

  it("rejects empty and oversized batches", () => {
    expect(verifySignatureSets([])).toBe(false);
    expect(verifySignatureSetsSameMessage([], message(1))).toEqual([]);

    const signingRoot = message(1);
    const indexedSet = {
      index: 0,
      message: signingRoot,
      signature: keys[0].sign(signingRoot).toBytes(),
      type: BLS_VERIFIER_SET_TYPE.indexed,
    } as const;
    expect(verifySignatureSets(Array.from({length: BLS_VERIFIER_MAX_BATCH_SIZE}, () => indexedSet))).toBe(true);
    expect(() => verifySignatureSets(Array.from({length: BLS_VERIFIER_MAX_BATCH_SIZE + 1}, () => indexedSet))).toThrow(
      "TooManySets"
    );

    const sameMessageSet = {index: 0, signature: indexedSet.signature};
    expect(
      verifySignatureSetsSameMessage(
        Array.from({length: BLS_VERIFIER_MAX_SAME_MESSAGE_BATCH_SIZE}, () => sameMessageSet),
        signingRoot
      )
    ).toEqual(Array.from({length: BLS_VERIFIER_MAX_SAME_MESSAGE_BATCH_SIZE}, () => true));
    expect(() =>
      verifySignatureSetsSameMessage(
        Array.from({length: BLS_VERIFIER_MAX_SAME_MESSAGE_BATCH_SIZE + 1}, () => sameMessageSet),
        signingRoot
      )
    ).toThrow("TooManySets");
  });

  it("rejects invalid numeric indices", () => {
    const signingRoot = message(1);
    const signature = keys[0].sign(signingRoot).toBytes();
    for (const index of [-1, 0.5, 2 ** 32, Number.NaN, Number.POSITIVE_INFINITY]) {
      expect(() =>
        verifySignatureSets([
          {
            index,
            message: signingRoot,
            signature,
            type: BLS_VERIFIER_SET_TYPE.indexed,
          },
        ])
      ).toThrow("InvalidUnsignedInteger");
      expect(() => verifySignatureSetsSameMessage([{index, signature}], signingRoot)).toThrow("InvalidUnsignedInteger");
    }
  });

  it("rejects malformed messages and returns false for invalid raw pubkeys", () => {
    const signingRoot = message(1);
    expect(() =>
      verifySignatureSets([
        {
          index: 0,
          message: new Uint8Array(31),
          signature: keys[0].sign(signingRoot).toBytes(),
          type: BLS_VERIFIER_SET_TYPE.indexed,
        },
      ])
    ).toThrow("InvalidMessageLength");

    expect(() =>
      verifySignatureSetsSameMessage([{index: 0, signature: new Uint8Array(96)}], new Uint8Array(31))
    ).toThrow("InvalidMessageLength");

    expect(
      verifySignatureSets([
        {
          message: signingRoot,
          pubkey: new Uint8Array(48),
          signature: keys[0].sign(signingRoot).toBytes(),
          type: BLS_VERIFIER_SET_TYPE.single,
        },
      ])
    ).toBe(false);
  });
});
